// Generated by CoffeeScript 1.7.1
var self;

if (typeof window === 'object') {
  self = window;
} else if (typeof global === 'object') {
  self = global;
} else {
  throw new Error('no global object found');
}

module.exports = self;
