// Generated by CoffeeScript 1.7.1
(function() {
  var INCLUDE_IGNORE, Keel,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Keel = {};

  INCLUDE_IGNORE = ['included'];

  Keel.include = function(obj) {
    var key, value;
    if (typeof obj !== 'object') {
      throw Error('aguments must be object');
    }
    for (key in obj) {
      value = obj[key];
      if (__indexOf.call(INCLUDED_IGNORE, key) < 0) {
        this.prototype[key] = value;
      }
    }
    if (typeof obj.included === 'function') {
      obj.included.call(this, this);
    }
    return this;
  };

  module.exports = Keel;

}).call(this);
