// Generated by CoffeeScript 1.7.1
var INCLUDE_IGNORE, hasProp, include,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

INCLUDE_IGNORE = ['included'];

hasProp = Object.prototype.hasOwnProperty;

include = function(obj) {
  var key, value;
  if (typeof obj !== 'object') {
    throw Error('aguments must be object');
  }
  for (key in obj) {
    value = obj[key];
    if (__indexOf.call(INCLUDED_IGNORE, key) < 0 && hasProp.call(obj, key)) {
      this.prototype[key] = value;
    }
  }
  if (typeof obj.included === 'function') {
    obj.included.call(this, this);
  }
  return this;
};

module.exports = include;
