// Generated by CoffeeScript 1.7.1
var Module, define, util;

util = require('./util');

Module = require('./module');

define = function(id, deps, factory) {
  var argsLen;
  argsLen = arguments.length;
  if (argsLen === 1) {
    factory = id;
    id = null;
  } else if (argsLen === 2) {
    factory = deps;
    if (util.is_a(id)) {
      deps = id;
      id = null;
    } else {
      deps = null;
    }
  }
  if (!util.is_a(deps) && util.is_f(factory)) {
    deps = util.getDeps(factory);
  }
  return Module.create(id, deps, factory);
};
