// Generated by CoffeeScript 1.7.1
var define, type;

type = require('./type');

define = function(id, deps, factory) {
  var argsLen;
  argsLen = arguments.length;
  if (argsLen === 1) {
    factory = id;
    return id = null;
  } else if (argsLen === 2) {
    factory = deps;
    if (type.is_a(id)) {
      deps = id;
      return id = null;
    }
  }
};
