// Generated by CoffeeScript 1.7.1
var Module, Script;

Script = require('./script');

Module = (function() {
  var FETCHED_MODULES, id2el_map, id2uri_map;

  FETCHED_MODULES = [];

  id2uri_map = {};

  id2el_map = {};

  Module.create = function(id, deps, factory) {};

  Module.get = function(id) {};

  Module.fetch = function(src) {
    return new Script(src);
  };

  function Module(id) {}

  Module.prototype.fetch = function() {
    return this.script = new Script;
  };

  return Module;

})();

module.exports = Module;
