// Generated by CoffeeScript 1.7.1
var Script, promise;

promise = require('./promise');

Script = (function() {
  var append, base, currentAddingScript, head, interactiveScript, remove, scripts;

  head = document.getElementsByTagName('head')[0];

  base = head.getElementsByTagName('base')[0];

  append = function(el) {
    if (base) {
      return head.insertBefore(el, base);
    } else {
      return head.appendChild(el);
    }
  };

  remove = function(el) {
    return head.removeChild(el);
  };

  scripts = head.getElementsByTagName('script');

  currentAddingScript = null;

  interactiveScript = null;

  Script.DEBUG = true;

  Script.getCurrentScript = function() {
    var script, _i, _len;
    if (currentAddingScript) {
      return currentAddingScript;
    }
    if (interactiveScript && interactiveScript.readyState === 'interactive') {
      return interactiveScript;
    }
    for (_i = 0, _len = scripts.length; _i < _len; _i++) {
      script = scripts[_i];
      if (script.readyState = 'interactive') {
        return interactiveScript = script;
      }
    }
  };

  function Script(src) {
    this._create();
    this.setUrl(src);
    this.deferred = promise.defer();
  }

  Script.prototype.setUrl = function(src) {
    if (src) {
      this.src = src;
    }
    if (this.src) {
      return this.el.src = this.src;
    }
  };

  Script.prototype._create = function() {
    this.el = document.createElement('script');
    this.el.type = 'text/javascript';
    this.el.charset = 'utf-8';
    return this.el.async = 'async';
  };

  Script.prototype.append = function() {
    this.addEvents();
    currentAddingScript = this.el;
    append(this.el);
    return currentAddingScript = null;
  };

  Script.prototype.remove = function() {
    return remove(this.el);
  };

  Script.prototype.addEvents = function() {
    if ('onload' in this.el) {
      this.el.onload = (function(_this) {
        return function() {
          return _this.onload();
        };
      })(this);
      return this.el.onerror = (function(_this) {
        return function() {
          return _this.onerror();
        };
      })(this);
    } else {
      return this.el.onreadystatechange = (function(_this) {
        return function() {
          var _ref;
          if ((_ref = _this.el.readyState) === 'loaded' || _ref === 'complete') {
            return _this.onload();
          }
        };
      })(this);
    }
  };

  Script.prototype.clearEvents = function() {
    return this.el.onload = this.el.onerror = this.el.onreadystatechange = null;
  };

  Script.prototype.onload = function() {
    this.deferred.resolve(this);
    this.clearEvents();
    if (!Script.DEBUG) {
      return this.remove();
    }
  };

  Script.prototype.onerror = function() {
    this.deferred.reject(this);
    this.clearEvents();
    if (!Script.DEBUG) {
      return this.remove();
    }
  };

  Script.prototype.then = function(done, fail) {
    return this.deferred.promise.then(done, fail);
  };

  return Script;

})();

module.exports = Script;
