// Generated by CoffeeScript 1.7.1
var uri;

uri = {
  extname: function(name) {
    return /(\.\w+)?$/.exec(name)[1];
  },
  isAbsolute: function(name) {
    name = '' + name;
    return name.charAt(0) !== '.';
  }
};

module.exports = uri;
